tokio-i3ipc seems too old, trying out 14
cargo install --git https://github.com/chmln/i3-auto-layout
    Updating git repository `https://github.com/chmln/i3-auto-layout`
  Installing i3-auto-layout v0.2.0 (https://github.com/chmln/i3-auto-layout#9e41eb38)
    Updating crates.io index
error: failed to compile `i3-auto-layout v0.2.0 (https://github.com/chmln/i3-auto-layout#9e41eb38)`, intermediate artifacts can be found at `/tmp/cargo-installg3vlAo`

Caused by:
  failed to select a version for the requirement `tokio-i3ipc = "^0.13.0"`
  candidate versions found which didn't match: 0.15.0, 0.14.0, 0.12.1, ...
  location searched: crates.io index
  required by package `i3-auto-layout v0.2.0 (/home/ad/.cargo/git/checkouts/i3-auto-layout-133bedf2910db070/9e41eb3)`